/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Wildan Abdul Rahman
 * 
 */
import koneksi.koneksidb;
import java.sql.*;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class formperlengkapan extends javax.swing.JFrame {

    private DefaultTableModel model;
    
    //deklarasi variabel
    String Kode_perlengkapan, Nama_perlengkapan, Jenis_perlengkapan, Harga;
    /**
     * Creates new form formperlengkapan
     */
    public formperlengkapan() {
        initComponents();
        model = new DefaultTableModel();
        
        //memberi nama header pada tabel
        tblperlengkapan.setModel(model);
        model.addColumn("Kode_perlengkapan");
        model.addColumn("Nama_perlengkapan");
        model.addColumn("Jenis_perlengkapan");
        model.addColumn("Harga");
        
        //fungsi ambil data
        getDataperlengkapan();
    }
    public void getDataperlengkapan(){
        //kosongkan tabel
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        
        //eksekusi koneksi dan kirimkan query ke database
        try{
            //tes koneksi
            Statement stat = (Statement) koneksidb.getKoneksi().createStatement();
            
            //perintah sql untuk membaca data dari tabel kategori        
            String sql = "SELECT * FROM Perlengkapan";
            ResultSet res = stat.executeQuery(sql);
            
            //baca data
            while(res.next()){
                //membuat obyek berjenis array
                Object[] obj = new Object[4];
                obj[0]=res.getString("Kode_perlengkapan");
                obj[1]=res.getString("Nama_perlengkapan");
                obj[2]=res.getString("Jenis_perlengkapan");
                obj[3]=res.getString("Harga");
                model.addRow(obj);
            }
        }catch(SQLException err){
           JOptionPane.showMessageDialog(null, err.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblperlengkapan = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jkode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jnama = new javax.swing.JTextField();
        jharga = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jjenis = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        tblKeluar = new javax.swing.JButton();
        tblHapus = new javax.swing.JButton();
        tblUbah = new javax.swing.JButton();
        tblReset = new javax.swing.JButton();
        tblSimpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("HARGA");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        tblperlengkapan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblperlengkapan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblperlengkapanMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblperlengkapan);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 470, 150));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("DATA PERLENGKAPAN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));
        getContentPane().add(jkode, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 172, -1));

        jLabel2.setText("KODE PERLENGKAPAN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 54, -1, -1));

        jLabel3.setText("NAMA PERLENGKAPAN");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 85, -1, -1));
        getContentPane().add(jnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 172, -1));
        getContentPane().add(jharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 172, -1));

        jLabel6.setText("JENIS PERLENGKAPAN");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 116, -1, -1));
        getContentPane().add(jjenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 172, -1));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblKeluar.setBackground(new java.awt.Color(255, 0, 0));
        tblKeluar.setText("X");
        tblKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblKeluarActionPerformed(evt);
            }
        });
        jPanel1.add(tblKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, -1));

        tblHapus.setText("HAPUS");
        tblHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblHapusActionPerformed(evt);
            }
        });
        jPanel1.add(tblHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));

        tblUbah.setText("UBAH");
        tblUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblUbahActionPerformed(evt);
            }
        });
        jPanel1.add(tblUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, -1, -1));

        tblReset.setText("RESET");
        tblReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblResetActionPerformed(evt);
            }
        });
        jPanel1.add(tblReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));

        tblSimpan.setText("SIMPAN");
        tblSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblSimpanActionPerformed(evt);
            }
        });
        jPanel1.add(tblSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void loadDataperlengkapan(){
        Kode_perlengkapan = jkode.getText();
        Nama_perlengkapan = jnama.getText();
        Jenis_perlengkapan = jjenis.getText();
        Harga = jharga.getText();
    }
    
    //memilih data saat baris pada tabel dipilih dengan mouse
    public void dataSelect(){
        //deklarasi variabel
        int i = tblperlengkapan.getSelectedRow();
        
        //uji adakah data di tabel?
        if(i == -1){
            //tidak ada yang terpilih atau dipilih.
            return;
        }
        jkode.setText(""+model.getValueAt(i,0));
        jnama.setText(""+model.getValueAt(i,1));
        jjenis.setText(""+model.getValueAt(i,2));
        jharga.setText(""+model.getValueAt(i,3));
    }
     
    //mengosongkan form
    public void reset(){
        Kode_perlengkapan = "";
        Nama_perlengkapan = "";
        Jenis_perlengkapan = "";
        Harga="";
        
        jkode.setText(Kode_perlengkapan);
        jnama.setText(Nama_perlengkapan);
        jjenis.setText(Jenis_perlengkapan);
        jharga.setText(Harga);
    }
    
    public void simpanDataPerlengkapan(){
        //panggil fungsi load data
        loadDataperlengkapan();
        
        //uji koneksi dan eksekusi perintah
        try{
            //test koneksi
            Statement stat = (Statement) koneksidb.getKoneksi().createStatement();
            
            //perintah sql untuk simpan data
            String  sql =   "INSERT INTO Perlengkapan(Kode_perlengkapan, Nama_perlengkapan, Jenis_perlengkapan,Harga)" + "VALUES('"+ Kode_perlengkapan +"','"+ Nama_perlengkapan +"','"+ Jenis_perlengkapan +"','"+ Harga+"')";
            PreparedStatement p = (PreparedStatement) koneksidb.getKoneksi().prepareStatement(sql);
            p.executeUpdate();
            
            //ambil data
           getDataperlengkapan();
        }catch(SQLException err){
            JOptionPane.showMessageDialog(null, err.getMessage());
        }
    }
    
    public void perbaruiDataPerlengkapan(){
        //fungsi load data kategori
        loadDataperlengkapan();
        
        try{
            //uji koneksi
            Statement stat = (Statement) koneksidb.getKoneksi().createStatement();
            
            //kirim perintah sql
            String sql = "UPDATE Perlengkapan SET Nama_perlengkapan = '"+ Nama_perlengkapan +"',Jenis_perlengkapan = '"+ Jenis_perlengkapan +"',Harga = '"+ Harga +"' WHERE Kode_perlengkapan = '"+ Kode_perlengkapan +"'";
            PreparedStatement p =(PreparedStatement)koneksidb.getKoneksi().prepareStatement(sql);
            p.executeUpdate();
            
            //ambil data
           getDataperlengkapan();
            
            //kosongkan data
            reset();
            JOptionPane.showMessageDialog(null, "PERUBAHAN DATA BERHASIL");
        }catch(SQLException err){
            JOptionPane.showMessageDialog(null, err.getMessage());
        }
    }
                                     
    public void hapusDataSiswa(){
        //panggil fungsi ambil data
        loadDataperlengkapan(); 
        
        //Beri peringatan sebelum melakukan penghapusan data
        int pesan = JOptionPane.showConfirmDialog(null, "HAPUS DATA"+ Kode_perlengkapan +"?","KONFIRMASI", JOptionPane.OK_CANCEL_OPTION);
        
        //jika pengguna memilih OK lanjutkan proses hapus data
        if(pesan == JOptionPane.OK_OPTION){
            //uji koneksi
            try{
                //buka koneksi ke database
                Statement stat = (Statement) koneksidb.getKoneksi().createStatement();
                
                //perintah hapus data
                String sql = "DELETE FROM Perlengkapan WHERE Kode_perlengkapan='"+ Kode_perlengkapan +"'";
                PreparedStatement p =(PreparedStatement)koneksidb.getKoneksi().prepareStatement(sql);
                p.executeUpdate();
                
                //fungsi ambil data
               getDataperlengkapan();
                
                //fungsi reset data
                reset();
                JOptionPane.showMessageDialog(null, "DATA BERHASIL DIHAPUS");
            }catch(SQLException err){
                JOptionPane.showMessageDialog(null, err.getMessage());
            }
        }
    }                     
                                     
    private void tblResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblResetActionPerformed
        //memanggil fungsi reset
        reset();
    }//GEN-LAST:event_tblResetActionPerformed

    private void tblUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblUbahActionPerformed
        //memanggil fungsi perbarui data kategori
        perbaruiDataPerlengkapan();
    }//GEN-LAST:event_tblUbahActionPerformed

    private void tblHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblHapusActionPerformed
        //memanggil fungsi hapus data kategori
        hapusDataPerlengkapan();
    }//GEN-LAST:event_tblHapusActionPerformed

    private void tblKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblKeluarActionPerformed
        //fungsi keluar dari master data kategori
        new formutamaa().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tblKeluarActionPerformed

    private void tblperlengkapanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblperlengkapanMouseClicked
        //memanggil fungsi memilih data
        dataSelect();
    }//GEN-LAST:event_tblperlengkapanMouseClicked

    private void tblSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblSimpanActionPerformed
        //memanggil fungsi simpan data kategori
        simpanDataPerlengkapan();
    }//GEN-LAST:event_tblSimpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formperlengkapan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formperlengkapan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formperlengkapan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formperlengkapan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formperlengkapan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jharga;
    private javax.swing.JTextField jjenis;
    private javax.swing.JTextField jkode;
    private javax.swing.JTextField jnama;
    private javax.swing.JButton tblHapus;
    private javax.swing.JButton tblKeluar;
    private javax.swing.JButton tblReset;
    private javax.swing.JButton tblSimpan;
    private javax.swing.JButton tblUbah;
    private javax.swing.JTable tblperlengkapan;
    // End of variables declaration//GEN-END:variables

    private void hapusDataPerlengkapan() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    loadDataperlengkapan(); 
        
        //Beri peringatan sebelum melakukan penghapusan data
        int pesan = JOptionPane.showConfirmDialog(null, "HAPUS DATA"+ Kode_perlengkapan +"?","KONFIRMASI", JOptionPane.OK_CANCEL_OPTION);
        
        //jika pengguna memilih OK lanjutkan proses hapus data
        if(pesan == JOptionPane.OK_OPTION){
            //uji koneksi
            try{
                //buka koneksi ke database
                Statement stat = (Statement) koneksidb.getKoneksi().createStatement();
                
                //perintah hapus data
                String sql = "DELETE FROM perlengkapan WHERE Kode_perlengkapan='"+ Kode_perlengkapan +"'";
                PreparedStatement p =(PreparedStatement)koneksidb.getKoneksi().prepareStatement(sql);
                p.executeUpdate();
                
                //fungsi ambil data
                getDataperlengkapan();
                
                //fungsi reset data
                reset();
                JOptionPane.showMessageDialog(null, "DATA TENDA SUDAH HILANG");
            }catch(SQLException err){
                JOptionPane.showMessageDialog(null, err.getMessage());
            }
        }
    }

    private void getDataPerlengkapan() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
