/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Wildan Abdul Rahman
 */
import koneksi.koneksidb;
import java.sql.*;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public final class tabeltenda extends javax.swing.JFrame {

    private static int getSelectedRow() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private static void setModel(DefaultTableModel model) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
//membuat objek    
    private final DefaultTableModel model;
    
    //deklarasi variabel
    String Kode_tenda, Nama_tenda, Jenis_tenda, Kapasitas, Harga;
    /**
     * Creates new form tabeltenda
     */
    public tabeltenda() {
        initComponents();
        //membuat obyek
        model = new DefaultTableModel();
        
        //memberi nama header pada tabel
        tabeltenda.setModel(model);
        model.addColumn("Kode_tenda");
        model.addColumn("Nama_tenda");
        model.addColumn("Jenis_tenda");
        model.addColumn("Kapasitas");
        model.addColumn("Harga");
        //fungsi ambil data
        getDatatenda();
    }
    //fungsi membaca data kategori
    public void getDatatenda(){
        //kosongkan tabel
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        
        //eksekusi koneksi dan kirimkan query ke database
        try{
            //tes koneksi
            Statement stat = (Statement) koneksidb.getKoneksi().createStatement();
            
            //perintah sql untuk membaca data dari tabel kategori        
            String sql = "SELECT * FROM tenda";
            ResultSet res = stat.executeQuery(sql);
            
            //baca data
            while(res.next()){
                //membuat obyek berjenis array
                Object[] obj = new Object[5];
                obj[0]=res.getString("Kode_tenda");
                obj[1]=res.getString("Nama_tenda");
                obj[2]=res.getString("Jenis_tenda");
                obj[3]=res.getString("Kapasitas");
                obj[4]=res.getString("Harga");
                model.addRow(obj);
            }
        }catch(SQLException err){
           JOptionPane.showMessageDialog(null, err.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tabeltenda = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txttenda = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        tblSimpan = new javax.swing.JButton();
        tblReset = new javax.swing.JButton();
        tblUbah = new javax.swing.JButton();
        tblHapus = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtjenis = new javax.swing.JComboBox<>();
        txtkapas = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtharga = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        tblKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabeltenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabeltenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabeltendaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabeltenda);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 382, 104));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("TABEL TENDA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));
        getContentPane().add(txttenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 51, 172, -1));

        jLabel2.setText("KODE TENDA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 54, -1, -1));

        jLabel3.setText("NAMA TENDA");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 85, -1, -1));
        getContentPane().add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 82, 172, -1));

        tblSimpan.setBackground(new java.awt.Color(255, 255, 255));
        tblSimpan.setText("SIMPAN");
        tblSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(tblSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, -1, -1));

        tblReset.setBackground(new java.awt.Color(255, 255, 255));
        tblReset.setText("RESET");
        tblReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblResetActionPerformed(evt);
            }
        });
        getContentPane().add(tblReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 70, -1));

        tblUbah.setBackground(new java.awt.Color(255, 255, 255));
        tblUbah.setText("UBAH");
        tblUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblUbahActionPerformed(evt);
            }
        });
        getContentPane().add(tblUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 120, 70, -1));

        tblHapus.setBackground(new java.awt.Color(255, 255, 255));
        tblHapus.setText("HAPUS");
        tblHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblHapusActionPerformed(evt);
            }
        });
        getContentPane().add(tblHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 70, -1));

        jLabel4.setText("KAPASITAS ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 147, -1, -1));

        jLabel5.setText("JENIS TENDA");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 116, -1, -1));

        txtjenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DOME", "LAYER", "SINGGLE", "JAVA" }));
        getContentPane().add(txtjenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 113, 172, -1));

        txtkapas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "4", "6", "8" }));
        getContentPane().add(txtkapas, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 144, 172, -1));

        jLabel6.setText("HARGA");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));
        getContentPane().add(txtharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 180, -1));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblKeluar.setBackground(new java.awt.Color(255, 0, 51));
        tblKeluar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tblKeluar.setText("X");
        tblKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblKeluarActionPerformed(evt);
            }
        });
        jPanel1.add(tblKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents
//membaca data 
    public void loadDatatenda(){
        Kode_tenda = txttenda.getText();
        Nama_tenda = txtNama.getText();
        Jenis_tenda = (String) txtjenis.getSelectedItem();
        Kapasitas = (String) txtkapas.getSelectedItem();
        Harga = txtharga.getText();
    }
    
    //memilih data saat baris pada tabel dipilih dengan mouse
    public void dataSelect(){
        //deklarasi variabel
        int i = tabeltenda.getSelectedRow();
        
        //uji adakah data di tabel?
        if(i == -1){
            //tidak ada yang terpilih atau dipilih.
            return;
        }
        txttenda.setText(""+model.getValueAt(i,0));
        txtNama.setText(""+model.getValueAt(i,1));
        txtjenis.setSelectedItem(""+model.getValueAt(i,2));
        txtkapas.setSelectedItem(""+model.getValueAt(i,3));
        txtharga.setText(""+model.getValueAt(i,4));
    }
     
    //mengosongkan form
    public void reset(){
        Kode_tenda = "";
        Nama_tenda = "";
        Jenis_tenda = "";
        Kapasitas = "";
        Harga = "";
               
        txttenda.setText(Kode_tenda);
        txtNama.setText(Nama_tenda);
        txtjenis.setSelectedItem(Jenis_tenda);
        txtkapas.setSelectedItem(Kapasitas);
        txtharga.setText(Harga);
    }
    
    public void simpanDatatenda(){
        //panggil fungsi load data
        loadDatatenda();
        
        //uji koneksi dan eksekusi perintah
        try{
            //test koneksi
            Statement stat = (Statement) koneksidb.getKoneksi().createStatement();
            
            //perintah sql untuk simpan data
            String  sql =   "INSERT INTO tenda(Kode_tenda, Nama_tenda, Jenis_tenda, Kapasitas, Harga)" + "VALUES('"+ Kode_tenda +"','"+ Nama_tenda +"','"+ Jenis_tenda +"','"+ Kapasitas +"','"+ Harga +"')";
            PreparedStatement p = (PreparedStatement) koneksidb.getKoneksi().prepareStatement(sql);
            p.executeUpdate();
            
            //ambil data
            getDatatenda();
        }catch(SQLException err){
            JOptionPane.showMessageDialog(null, err.getMessage());
        }
    }
    
    public void perbaruiDataSiswa(){
        //fungsi load data kategori
        loadDatatenda();
        
        try{
            //uji koneksi
            Statement stat = (Statement) koneksidb.getKoneksi().createStatement();
            
            //kirim perintah sql
            String sql = "UPDATE tenda SET Nama_tenda = '"+ Nama_tenda +"' WHERE Kode_tenda = '"+ Kode_tenda +"'";
            PreparedStatement p =(PreparedStatement)koneksidb.getKoneksi().prepareStatement(sql);
            p.executeUpdate();
            
            //ambil data
            getDatatenda();
            
            //kosongkan data
            reset();
            JOptionPane.showMessageDialog(null, "PERUBAHAN DATA BERHASIL");
        }catch(SQLException err){
            JOptionPane.showMessageDialog(null, err.getMessage());
        }
    }
                                     
    public void hapusDatatenda(){
        //panggil fungsi ambil data
        loadDatatenda(); 
        
        //Beri peringatan sebelum melakukan penghapusan data
        int pesan = JOptionPane.showConfirmDialog(null, "HAPUS DATA"+ Kode_tenda +"?","KONFIRMASI", JOptionPane.OK_CANCEL_OPTION);
        
        //jika pengguna memilih OK lanjutkan proses hapus data
        if(pesan == JOptionPane.OK_OPTION){
            //uji koneksi
            try{
                //buka koneksi ke database
                Statement stat = (Statement) koneksidb.getKoneksi().createStatement();
                
                //perintah hapus data
                String sql = "DELETE FROM tenda WHERE Kode_tenda='"+ Kode_tenda +"'";
                PreparedStatement p =(PreparedStatement)koneksidb.getKoneksi().prepareStatement(sql);
                p.executeUpdate();
                
                //fungsi ambil data
                getDatatenda();
                
                //fungsi reset data
                reset();
                JOptionPane.showMessageDialog(null, "DATA TENDA SUDAH HILANG");
            }catch(SQLException err){
                JOptionPane.showMessageDialog(null, err.getMessage());
            }
        }
    }
    private void tblKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblKeluarActionPerformed
        //fungsi keluar dari master data kategori
        new formutamaa().setVisible(true);
        this.dispose();
       
    }//GEN-LAST:event_tblKeluarActionPerformed

    private void tabeltendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabeltendaMouseClicked
        //memanggil fungsi memilih data
        dataSelect();
    }//GEN-LAST:event_tabeltendaMouseClicked

    private void tblSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblSimpanActionPerformed
        //memanggil fungsi simpan data kategori
        simpanDatatenda();
    }//GEN-LAST:event_tblSimpanActionPerformed

    private void tblResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblResetActionPerformed
        //memanggil fungsi reset
        reset();
    }//GEN-LAST:event_tblResetActionPerformed

    private void tblUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblUbahActionPerformed
        //memanggil fungsi perbarui data kategori
        perbaruiDatatenda();
        reset();
    }//GEN-LAST:event_tblUbahActionPerformed

    private void tblHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblHapusActionPerformed
        //memanggil fungsi hapus data kategori
        hapusDatatenda();
    }//GEN-LAST:event_tblHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tabeltenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tabeltenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tabeltenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tabeltenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tabeltenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabeltenda;
    private javax.swing.JButton tblHapus;
    private javax.swing.JButton tblKeluar;
    private javax.swing.JButton tblReset;
    private javax.swing.JButton tblSimpan;
    private javax.swing.JButton tblUbah;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtharga;
    private javax.swing.JComboBox<String> txtjenis;
    private javax.swing.JComboBox<String> txtkapas;
    private javax.swing.JTextField txttenda;
    // End of variables declaration//GEN-END:variables

    private void perbaruiDatatenda() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        loadDatatenda();
        
        //uji koneksi dan eksekusi perintah
        try{
            //test koneksi
            Statement stat = (Statement) koneksidb.getKoneksi().createStatement();
            
            //perintah sql untuk simpan data
            String  sql =  ( "UPDATE tenda set Nama_tenda='"+txtNama.getText()+"', Jenis_tenda='"+txtjenis.getSelectedItem()+"', Kapasitas='"+txtkapas.getSelectedItem()+"', Harga='"+txtharga.getText()+"'where Kode_tenda='"+txttenda.getText()+"'"); 
            PreparedStatement p = (PreparedStatement) koneksidb.getKoneksi().prepareStatement(sql);
            p.executeUpdate();
            
            //ambil data
            getDatatenda();
        }catch(SQLException err){
            JOptionPane.showMessageDialog(null, err.getMessage());
        }
    }


    /*private void perbaruiDatatenda() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /*private void simpanDatatenda() {
    throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }*/
}